### ISSUE TITLE
Add lang parameter to tweet search

### ISSUE THREAD

**Issue by teopost** [python-twitter-tools/twitter#292]
It would be very useful to add a parameter to limit the search to a specific language tweet

**Comment by diegoaguilar** [comment]
You can actually do it:

`iterator = twitter_stream.statuses.filter(track=query_term,language='es', stall_warnings=True)`

**Comment by teopost** [comment]
I think it should be a parameter of search method

**Comment by RouxRC** [comment]
@teopost are you talking about the command line interface ?
