### ISSUE TITLE
Unable to archive DMs

### ISSUE THREAD

**Issue by norosa** [python-twitter-tools/twitter#333]
I ran this:

```
twitter-archiver -o -d IRLNoah
```

I then authenticated with Twitter and gave the tool access. I then get an error.

The error contains this:

```
This application is not allowed to access or delete your direct messages.
```

Any clue?

**Comment by hugovk** [comment]
That's probably my fault: I requested write amd access DM permissions removed becauseI didn't realise it can also archive DMs, see https://github.com/sixohsix/twitter/issues/327

@StalkR, I guess you'd better flip the switch back.

Sorry for the hassle!

**Comment by hugovk** [comment]
That's probably my fault: I requested write and access DM permissions removed because I didn't realise it can also archive DMs, see https://github.com/sixohsix/twitter/issues/327

@StalkR, I guess you'd better flip the switch back.

Sorry for the hassle!

**Comment by StalkR** [comment]
Reverted back to _Read, Write and Access direct messages_
