### ISSUE TITLE
Unable to determine why twitterstream ends automatically..

### ISSUE THREAD

**Issue by NumberChiffre** [python-twitter-tools/twitter#337]
Hello Everyone,

I noticed that my twitterparser automatically terminates randomly. I think this is because the steam terminates, but I have no clue why it terminates automatically and how come no error or any message returns from this termination. 

I believe there is some issue on the socket level and I would really appreciate if anyone can shed some light on this issue. 

Thank you and I look forward to your replies!

Terence

**Comment by boogheta** [comment]
Hi,
It can happen that Twitter closes the connexion on the remote side, or that your collection is too slow, or that your internet connexion  briefly stopped breaking the stream and so on, so you should usually run it in an infinite loop, such as something like : 
```python
while True:
    try:
        for msg in stream.statuses.filter(track="foo,bar", filter_level='none', stall_warnings='true'):
                if not msg or msg.get("timeout"):
                    continue
                if msg.get("disconnect") or msg.get("hangup"):
                    print("WARNING Stream connection lost: %s" % msg)
                    break
                if msg.get('text'):
                    process_tweet(msg)
                else:
                    print("INFO: Got special message: %s" % str(msg))
    except(TwitterHTTPError, BadStatusLine, URLError, SSLError, socket.error) as e:
        print("WARNING: Stream connection lost, reconnecting in a sec... (%s: %s)" % (type(e), e)):
```

**Comment by NumberChiffre** [comment]
@boogheta 
Thank you a lot for replying to me! I implemented your code and it seems I got disconnected and hangup became true at some point, is there a way to properly re-establish the connection once this happens?

**Comment by boogheta** [comment]
Great. I'll let you close the issue then if you're satisfied :)

**Comment by boogheta** [comment]
although it could remain as documentation if we rename it

**Comment by NumberChiffre** [comment]
@boogheta 
Hello again, 

The code you provided with to handle the exceptions worked well! But it seems I hit a lot of URLError over the past 2 days. Once it hits, it stops and my computer goes to sleep. I can only make my program run again once I re-login. 

Is there any way to avoid this? And for sure I want to keep this as documentation, hopefully other people can make use of it!

Thank you!

**Comment by boogheta** [comment]
Hi,
Not sure I get your issue.
There is really no reason your script would log out your computer, it sounds more like you have an automatic shutdown set on your OS...
