### ISSUE TITLE
twitterstream slows down and misses important tweets..

### ISSUE THREAD

**Issue by NumberChiffre** [python-twitter-tools/twitter#340]
Hello Everyone,

I've noticed that the twitterstream slows down at some point after running it for hours. What I did is reconnect to the twitterstream at each 5000 iterations, now I'm doing it for every 100 iterations. 

Is there any good ways to avoid twitterstream from missing tweets other than reconnecting at every 100 iterations? 

Thank you!

Sincerely,
Terence Liu

**Comment by boogheta** [comment]
I've never noticed any such behavior in multiple years of using it, and it is impossible to help you without knowing more about your use, can you share your code and the stream/keywords you're tracking so it can be tested/reproduced?
What can happen is that you receive a heavy load of tweets which your code takes more time to handle than to receive, hence making you accumulate delay an at some point miss tweets. 
Another possible cause is that Twitter does not guarantee returning all tweets if you follow too many verbose keywords in the same query as they won't send more than some maximum number of tweet per connection per second.
Twitter usually notifies you in such cases with warnings (see here https://dev.twitter.com/streaming/overview/messages-types ).
If these are the causes of your issue, you could try and run the collection and the postprocessing in separate processes.

**Comment by boogheta** [comment]
I would first start by printing in stderr objects returned by the stream that don' match the `if tweet.get('text'):` to check whether you get warning messages from Twitter.
It might be related to the fact that you're doing network queries (the bitcoin value check) which could result in timeouts and slow down your process but considering your volume (less than a tweet every 2 seconds) it shouldn't really impact much...

To try and get missed tweets separately, you can try and query the search API concurrently regularly but that will require to run the two processes separately in two threads or processes as I was suggesting in the last sentence. I do that in this code if you want an example : https://github.com/medialab/gazouilloire/blob/master/gazouilloire/run.py

**Comment by NumberChiffre** [comment]
@boogheta Thank you very much for your reply and the example! I think in your twitter homepage, there is a "search" function. Is it the same as the link you provided? Because I didn't find that specific function in your files.

**Comment by boogheta** [comment]
@NumberChiffre As explained in the homepage's doc, this twitter library exposes all of Twitter's api functions documented here https://dev.twitter.com/rest/public
So the search/tweets route https://dev.twitter.com/rest/reference/get/search/tweets can be called doing twitterconn.search.tweets(api_arguments) like for instance here https://github.com/medialab/gazouilloire/blob/master/gazouilloire/run.py#L325-L339
