### ISSUE TITLE
Character limit for API?

### ISSUE THREAD

**Issue by slackhead** [python-twitter-tools/twitter#377]
Hi. I'm seeing truncated tweets at much less than the 280 char limit it seems.

Example from stephenfry:

In LA on 26th Feb? @letterslive with @driverminnie, @JKCorden, @HamillHimself me, Jarvis Cocker, Ian McShane, +   MAN...

The actual tweet:

In LA on 26th Feb? @letterslive with @driverminnie, @JKCorden, @HamillHimself me, Jarvis Cocker, Ian McShane, + MANY surprises. In aid of http://826LA.org  and @WomenforWomen - https://vimeo.cosylm/252748387/702b9cdae3
Tickets here -

Links to tweet:

https://twitter.com/i/web/status/963316948321882112

Any idea why this is happening?

**Comment by RouxRC** [comment]
This is because you need to use the "extended" tweet_mode argument to your api calls now to get tweets with full text, and use the field full_text instead of text, see examples and links in #369

**Comment by slackhead** [comment]
But this is with the CLI. I can't see any command line options for extended tweets.

**Comment by ResponSySS** [comment]
Hi,
I got the same problem using the CLI tool (`twitter set` command) for my Twitter bot which can be found at this adress: https://twitter.com/YoureNotYourTL/
Example : https://twitter.com/YoureNotYourTL/status/962362777217191936 + https://twitter.com/YoureNotYourTL/status/962362779092111360

**Comment by RouxRC** [comment]
Hi,
Yes no one is maintaining the CLI tools, so they need to be adapted as was done for twitter archiver in #371.
These are quite easy fixes to implement, pull requests are very welcome!

**Comment by ResponSySS** [comment]
Actually it seems tweeting 141+ char tweet is causing the CLI to hang in infinite loop, even after I started trying to fix it (140 char limit in class `SetStatusAction` in `twitter/cmdline.py`).

**Comment by RouxRC** [comment]
Can you share your fix attempt?

**Comment by slackhead** [comment]
Ok. I have this working for commands, but when using the userstream I still get 140 char tweets still.
Python:

`kwargs = dict(tweet_mode='extended')
stream = TwitterStream(auth=OAuth(                                                      
                    oauth_token, oauth_secret, CONSUMER_KEY, CONSUMER_SECRET),                          
                                      api_version='1.1', domain="userstream.twitter.com",               
                                      **stream_options)

tweet_iter = stream.user(**kwargs)

for tweet in tweet_iter:
if ...
elif tweet.get('full_text') or tweet.get('text'):
etc...
`

Any ideas?

**Comment by slackhead** [comment]
I just had this message from a twitter dev:

User streams has been deprecated and we plan to sunset it soon. I encourage you to build on fully supported API.

So the question now is how to adapt it to the api.twitter.com and how to keep it updating.

**Comment by RouxRC** [comment]
I've never played with the userstream, but in the regular stream the returned tweets contain a new object `extended_tweet` which contains the `full_text` : https://developer.twitter.com/en/docs/tweets/tweet-updates

But userstream is supposed to disappear indeed so you might want to shift to rest api routes such as these, it depends what you want to grab: https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-home_timeline.html
