### ISSUE TITLE
A direct messages tutorial is harassing a Twitter user

### ISSUE THREAD

**Issue by sixohsix** [python-twitter-tools/twitter#378]
Somewhere on the Internet is a tutorial about interfacing Python and Twitter (possibly with Python Twitter Tools) to send direct messages. This tutorial has sample code that, when runs, sends a specific user a direct message with the text:

_"I'm a big fan of your work"_

While the intent is probably nice, the user is being disturbed by the pile of noise cluttering up their direct messages list, and would like it to stop.

If you know of such a tutorial with that message, please let me know so I can contact the author to get it changed. And if you wrote such a tutorial, please change the recipient and let me know that you did so.

**Comment by sixohsix** [comment]
cc @RouxRC @hugovk , just in case you've seen this going around.

**Comment by RouxRC** [comment]
haven't heard of it nope, although I can well imagine how this could happen :/
