### ISSUE TITLE
Autodeploy to PyPI

### ISSUE THREAD

**Issue by hugovk** [python-twitter-tools/twitter#422]
As suggested in https://github.com/sixohsix/twitter/issues/356, I'll set up automated deploys:

* Deploy to TestPyPI on merge to master, to make sure the release mechanism is working smoothly and avoid surprises on release day
* Deploy to production PyPI for GitHub releases/tags

I've set up a test `twitter` project on TestPyPI.

@RouxRC If you create an account on https://test.pypi.org, I'll give you access too.

Then, to use https://github.com/pypa/gh-action-pypi-publish, we then need to create API tokens for TestPyPI and PyPI and store them as secrets under https://github.com/sixohsix/twitter/settings.

TODO:

1. Add an API token called (say) `twitter-ci` at https://test.pypi.org/manage/account/token/
2. Paste the token as `TEST_PYPI_PASSWORD` at https://github.com/sixohsix/twitter/settings/secrets/actions/new
3. Repeat for production PyPI https://pypi.org/manage/account/token/, save as `PYPI_PASSWORD`

More info on PyPI API tokens: https://pypi.org/help/#apitoken

I don't have access to https://github.com/sixohsix/twitter/settings. @RouxRC Please could you either give me access to that, or please could you follow the instructions above to add the tokens?

**Comment by RouxRC** [comment]
Great!
I created a `boogheta` account on Pypi test as well.
But I don't have access to the repo settings on Github yet actually, I guess there is still one last "small" thing we shall ask @sixohsix, which is admin rights to the repo, pretty please :)

**Comment by hugovk** [comment]
✅ Invited `boogheta` to TestPyPI

**Comment by polm** [comment]
I realize this is kind of an old issue, but as a note, you can't grant access to settings to other people on a user-owned repository. From the [Github help](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-an-environment:~:text=To%20create%20secrets%20for%20an%20environment%20in%20a%20user,repository%2C%20you%20must%20have%20admin%20access.):

> To create secrets for an environment in a user account repository, you must be the repository owner. To create secrets for an environment in an organization repository, you must have admin access.

This has bitten me on a repo I inherited. What I did as a workaround is do the PyPI uploads from a personal fork.

**Comment by hugovk** [comment]
Aha, good to know, thanks!

Creating a dedicated organisation for the repo was suggested in https://github.com/sixohsix/twitter/issues/356, shall go ahead with that?

If so, the next challenge is [naming things](https://martinfowler.com/bliki/TwoHardThings.html)!

Already taken:

* `https://github.com/twitter`
* `https://github.com/python-twitter`
* `https://github.com/ptt`

Not taken:

* `https://github.com/python-twitter-tools`
* `https://github.com/twitter-python`
* `https://github.com/ptt-dev`
* `https://github.com/python-twitter-dev`
* `https://github.com/twitter-tools`
* ?

**Comment by RouxRC** [comment]
Hey @hugovk! Apologies for my late answer!
It's not an easy choice to make, I guess since it's the original name of the project python-twitter-tools might be the best choice, although to better match the fact the pypi project is named twitter, maybe just twitter-python would be better, also considering the CLI tools parts of the project are not actually really maintained contrary to the python lib part.
So I would be in favor of those two, with a small preference for the second. What's your opinion?
Also, I'm taking the opportunity while answering this to ping again @sixohsix: we won't bother you anymore afterwards I think, but that would be really useful if you could take a few minutes one last time to just set @hukovk and myself admins of the repo so that we would be able to do all leftovers migrations operations. Thanks a lot in advance!

**Comment by RouxRC** [comment]
All right, since it's for the organization name anyway, I guess keeping the original library name makes the most sense.
I let you go forward and create the organization @hugovk?
I will try and e-mail Mike for the settings access since I feel like he's not reading these anymore at all :)

**Comment by hugovk** [comment]
@RouxRC I've created the https://github.com/python-twitter-tools org and invited you and Mike.

**Comment by RouxRC** [comment]
Thanks!

**Comment by sixohsix** [comment]
I transferred ownership of the repo to the organization. Please let me know if there is more I should do to enable your work.

**Comment by hugovk** [comment]
Thank you! I've made you both owners of the org as well, and added the PyPI API tokens to https://github.com/python-twitter-tools/twitter/settings/secrets/actions

I'll get the rest of the autodeploy set up later.

**Comment by RouxRC** [comment]
Lots of thanks @sixohsix & @hugovk!

**Comment by RouxRC** [comment]
Hey Hugo, seems like some authentication to PyPi is still missing: https://github.com/python-twitter-tools/twitter/runs/2711860451?check_suite_focus=true
Any idea what misses?

**Comment by RouxRC** [comment]
Hey Hugo, seems like some authentication to PyPi is still missing: https://github.com/python-twitter-tools/twitter/runs/2711860451?check_suite_focus=true
Any idea what misses?

**Comment by RouxRC** [comment]
Found it, the token was missing, I recreated it and set it in the repo settings and it works now!
Will try to make a new release now!

**Comment by RouxRC** [comment]
And it worked, version 1.19 with all changes from the past 2 years finally shipped! Thanks again @hugovk and @sixohsix, the process will be so much easier now!

**Comment by hugovk** [comment]
Great, thank you for releasing!
