### ISSUE TITLE
retweeters id don't go to

### ISSUE THREAD

**Issue by ebenezergraham** [python-twitter-tools/twitter#462]
GET statuses/retweeters/ids id doesn't go to the end of url as assumed in on this [line](https://github.com/python-twitter-tools/twitter/blob/master/twitter/api.py#L186). 

This introduces a bug for this endpoint

[Example](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/get-statuses-retweeters-ids#:~:text=GET%20https%3A//api.twitter.com/1.1/statuses/retweeters/ids.json%3Fid%3D327473909412814850%26count%3D100%26stringify_ids%3Dtrue)

**Comment by boogheta** [comment]
As the documentation explains in the examples [here](https://github.com/python-twitter-tools/twitter#the-twitter-class), you should call for those routes using `_id` arg instead of `id`

**Comment by ebenezergraham** [comment]
Ah, I see. thanks for the prompt correction.
