### ISSUE TITLE
May I ask whether the free api key can obtain the latest tweets of a user? I want to realize a tg robot to automatically push the latest tweets of a specified person. Can the free version be realized

### ISSUE THREAD

**Issue by 2622594863** [python-twitter-tools/twitter#472]
May I ask whether the free api key can obtain the latest tweets of a user? I want to realize a tg robot to automatically push the latest tweets of a specified person. Can the free version be realized

**Comment by boogheta** [comment]
I don't believe so. My understanding of the remaining free APIs is it mostly allows only to post tweets, not to collect them, but maybe it changed since last time I checked

**Comment by huojiecs110** [comment]
> May I ask whether the free api key can obtain the latest tweets of a user? I want to realize a tg robot to automatically push the latest tweets of a specified person. Can the free version be realized

The free version has too many restrictions~ Welcome to experience my api service twitter.utools.me ApiDoc: https://utools.readme.io/
