### ISSUE TITLE
Tarballs should include tests

### ISSUE THREAD

**Issue by djc** [python-twitter-tools/twitter#93]
It's useful for package management to have tarballs that include the tests. Please include the tests in the tarballs on PyPI. It would also help if the tarballs contained the README and if the README contained information on dependencies (specifically what versions of Python this has been tested against).

**Comment by mcepl** [comment]
+1 from me for openSUSE packaging.

**Comment by hugovk** [comment]
If no one creates a PR before October, ping me and I'll make one for this issue's 10th birthday! ;)

We should probably exclude this project's OAuth credentials from the sdist; downstream testers should create their own on their own accounts because otherwise it eats up this project's rate limits.

**Comment by sebix** [comment]
> We should probably exclude this project's OAuth credentials from the sdist; downstream testers should create their own on their own accounts because otherwise it eats up this project's rate limits.

Why don't you provide the credentials in the repo then? The better way would be to save them as secrets in the CI.

I may create a PR for that issue in the next days.

**Comment by mcepl** [comment]
> We should probably exclude this project's OAuth credentials from the sdist; downstream testers should create their own on their own accounts because otherwise it eats up this project's rate limits.

Shouldn’t you have split tests into unit tests and integration tests anyway? The former should use mocked interfaces anyway, so no credentials are needed (and that’s what I would use for testing while packaging for openSUSE, distributions don’t have network access in their build systems anyway) and the latter would be used only by true developers.

**Comment by hugovk** [comment]
Yes, these are great suggestions, PRs welcome!

I can see value for leaving credentials in the repo for forks to use, but mocking the interfaces would be great.
